version: '3.1'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bitcoin_analytics
      MYSQL_USER: utxo
      MYSQL_PASSWORD: password
    ports:
      - "6603:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "7936:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
